spring:
  application:
    name: "ecommerce-order-payment-system"
  datasource:
    url: jdbc:mysql://localhost:3306/fastcampus?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA ??
  jpa:
    hibernate:
      ddl-auto: none # DB ??? ?? (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # ?? ?? ?? (??)
        show_sql: true       # ?? ?? ??
  kafka:
    bootstrap-servers: [
      "localhost:19094"
    ]
    group-id: "settlements_1"
    schema-registry-url: "http://localhost:8085"
---
spring:
  config:
    activate:
      on-profile: dev-docker
  datasource:
    url: jdbc:mysql://mysql:3306/fastcamp_labs?serverTimezone=UTC&characterEncoding=UTF-8
    username: fastcamp
    password: testlabs
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: none # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
  jdbc:
    template:
      batch-size: 100
  kafka:
    bootstrap-servers: [
      "kafka:19092"
    ]
    group-id: "settlements_1"
    schema-registry-url: "http://172.26.0.13:8085"
---
spring:
  config:
    activate:
      on-profile: aws
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # DB 초기화 전략 (none, create, create-drop, update, validate)
    properties:
      hibernate:
        auto_quote_keyword: false
        globally_quoted_identifiers: false
        format_sql: true     # 쿼리 로그 포맷 (정렬)
        show_sql: true       # 쿼리 로그 출력
  jdbc:
    template:
      batch-size: 100
  kafka:
    bootstrap-servers: [
      "172.31.39.184:30094"
    ]
    group-id: "settlements_1"
    schema-registry-url: "http://172.31.39.184:30085"

pg:
  tosspayments:
    baseUrl: "https://api.tosspayments.com/"
    privateKey: "test_sk_0RnYX2w532257LzwRYBK3NeyqApQ"

my:
  name: hyeonjin_dev
  age: 30

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE


