apiVersion: apps/v1
kind: Deployment

metadata:
  name: kafka-ui-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-deployment
  template:
    metadata:
      labels:
        app: kafka-ui-deployment
    spec:
      containers:
        - name: kafka-ui-container
          image: provectuslabs/kafka-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: KAFKA_CLUSTERS_0_NAME
              value: Fast-Ecommerce-Kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka-service:19092
---
apiVersion: v1
kind: Service

metadata:
  name: kafka-ui-service

spec:
  type: NodePort
  selector:
    app: kafka-ui-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081