apiVersion: apps/v1
kind: Deployment

metadata:
  name: kafka-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
        - name: kafka-container
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 19092
            - containerPort: 19094
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INTERNAL://kafka-service:19092,EXTERNAL://localhost:19094
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: INTERNAL
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_LISTENERS
              value: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:30094
            - name: KAFKA_AUTO_CREATE_TOPIC_ENABLE
              value: "false"
---
apiVersion: v1
kind: Service

metadata:
  name: kafka-service

spec:
  type: NodePort
  selector:
    app: kafka-deployment
  ports:
    - protocol: TCP
      name: internal
      port: 19092
      targetPort: 19092
    - protocol: TCP
      name: external
      port: 19094
      targetPort: 19094
      nodePort: 30094
