#쿠버네티스를 사용하기 위해 이런 리소스 파일을 yaml 파일로 작성하게 되는데 pod 말고도 service, deployment, pod 등등.. 이러한 파일들을 메니페스트 파일이라고 부른다 (Manifest file)
apiVersion: v1
kind: Pod #파드라는 종류를 만들거다

metadata: #pod의 기본적인 정보를 기입
  name: nginx-pod-1

spec: #pod의 세부 정보
  containers: #pod 하나에는 하나의 컨테이너가 들어가 있는데 그 컨테이너의 정보
    - name: nginx-container #이 이름은 다른걸로 바꿔도 됨
      image: nginx #nginx라는 이미지를 쓸거다 nginx:latest 이렇게 태그 붙여도 됨 안붙이면 자연스럽게 최신버전
      ports:
        - containerPort: 80 #단순히 가독성을 위한 옵션

# 이렇게 하면 외부에서 접속이 되지 않는다.
# 1. pod 내부로 들어가서 연결 확인 하는 방법
#   kubectl exec -it nginx-pod -- bash
#   curl localhost:80 -> 응답 날라옴
# 2. 포트 포워딩 (포트 연결)
#   kubectl port-forword pod/nginx-pod 80(로컬에서의 port):80(pod에서의 port)
---
apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod-2

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod

metadata:
  name: nginx-pod-3

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
# 이렇게 하면 pod가 3개 띄워진다.
# 하지만 이렇게 하나씩 적어주면 100개 증설할 땐 ? 어려움 -> deployment 활용