apiVersion: v1
kind: Service

metadata:
  name: nginx-service #Service 이름

#Service 세부 정보
spec:
  type: NodePort #Service의 종류
  selector:
    app: nginx-deployment-app
    #여러 파드에 연결을 시켜야한다. 여러 트래픽을 분배해서 보내줘야하는데 어떤 파드들에게 트래픽을 보내주느냐를 결정하는 것
    # kind가 Deployment의 메니페스트 파일에 가보면 template/metadata/lables/app: 에 등록된 이름을 여기에 적어준다.
  ports:
    - protocol: TCP
      port: 9000 # 쿠버네티스 내부에서 Service에 접속하기 위한 포트 번호
      targetPort: 80 # 매핑하기 위한 파드의 포트 번호
      nodePort: 30000 #외부에서 사용자들이 접근하게 될 포트 번호