apiVersion: apps/v1
kind: Deployment

metadata:
  name: zookeeper-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-deployment
  template:
    metadata:
      labels:
        app: zookeeper-deployment
    spec:
      containers:
        - name: zookeeper-container
          image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
---
apiVersion: v1
kind: Service

metadata:
  name: zookeeper-service

spec:
  type: ClusterIP
  selector:
    app: zookeeper-deployment
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
